server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: skyvault-backend

  data:
    mongodb:
      uri: mongodb://localhost:27017/skyvault_db
      auto-index-creation: true

app:
  jwt-secret: 9a2f8c4e7b1a5d3f8e6c4b2a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f1e
  jwt-expiration-milliseconds: 86400000 # 24 hours
